stages:
  - pre-deploy
  - deploy

variables:
  APP_PATH: /home/ubuntu/apps/mezuu.id
  BUN_PATH: /home/ubuntu/.bun/bin/bun

clone-and-install:
  stage: pre-deploy
  script:
    - cd ${APP_PATH}
    - git checkout master
    - git pull origin master
    - ${BUN_PATH} i
  tags:
    - oracle

build-and-run:
  stage: deploy
  script:
    - cd ${APP_PATH}
    - ${BUN_PATH} run build
  tags:
    - oracle
