stages:
  - pre-deploy
  - deploy

variables:
  APP_PATH: ~/apps/mezuu.id
    
clone-and-install:
  stage: pre-deploy
  script:
    - ls
    - cd ${APP_PATH}
    - git checkout master
    - git pull origin master
    - bun i
  tags:
    - oracle

build-and-run:
  stage: deploy
  script:
    - cd ${APP_PATH}
    - bun run build
  tags:
    - oracle
