services:
  web:
    image: __IMAGE__
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mezuu-id.rule=Host(`mezuu.id`)"
      - "traefik.http.routers.mezuu-id.entrypoints=web,websecure"
      - "traefik.http.routers.mezuu-id.service=mezuu-id"
      - "traefik.http.services.mezuu-id.loadbalancer.server.port=3000"
      - "traefik.http.routers.mezuu-id.tls=true"
      - "traefik.docker.network=traefik_traefik"
